src/Entity/DeckCards.php
<?php

namespace App\Entity;

use App\Repository\DeckCardsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DeckCardsRepository::class)]
class DeckCards
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?string $card_id = null;

    #[ORM\Column]
    private ?int $deckId = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCardId(): ?string
    {
        return $this->card_id;
    }

    public function setCardId(string $card_id): self
    {
        $this->card_id = $card_id;

        return $this;
    }

    public function getDeckId(): ?int
    {
        return $this->deckId;
    }

    public function setDeckId(int $deckId): self
    {
        $this->deckId = $deckId;

        return $this;
    }
}

src/Entity/Decks.php
<?php

namespace App\Entity;

use App\Repository\DecksRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DecksRepository::class)]
class Decks
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $name = null;

    #[ORM\Column]
    private int $upvotes = 0;

    #[ORM\Column]
    private int $downvotes = 0;

    #[ORM\Column(nullable: true)]
    private ?int $owner = null;

    public function getId(): int
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getUpvotes(): int
    {
        return $this->upvotes;
    }

    public function setUpvotes(int $upvotes): self
    {
        $this->upvotes = $upvotes;

        return $this;
    }

    public function getDownvotes(): int
    {
        return $this->downvotes;
    }

    public function setDownvotes(int $downvotes): self
    {
        $this->downvotes = $downvotes;

        return $this;
    }

    public function getOwner(): ?int
    {
        return $this->owner;
    }

    public function setOwner(?int $owner): self
    {
        $this->owner = $owner;

        return $this;
    }
}

src/Controller/CardController.php
<?php

namespace App\Controller;

use App\Repository\DecksRepository;
use App\Service\CardService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class CardController extends AbstractController
{

    #[Route('cards/', name: 'cards')]
    public function getCards(Request $request, CardService $service): Response
    {
        $color = $request->query->get('color');
        $q = $request->query->get('q');

        $cards = $this->json($service->getAllCards($color, $q)->toArray())->getContent();

        $data = json_decode($cards, true);

        return $this->render('card/list.html.twig', [
            'title' => 'MTG Cards',
            'cards' => $data['cards'],
        ]);
    }

    #[Route('cards/{id}', name: 'card_view')]
    public function cardDetails($id, CardService $service, DecksRepository $decksRepository): Response
    {
        $card = $this->json($service->getCardsById($id)->toArray())->getContent();

        $data = json_decode($card, true);

        $decks = $decksRepository->findAll();



        //dd($decks);
        //dd($data['card']['legalities']);

        return $this->render('card/view.html.twig', [
            'title' => 'MTG Cards',
            'card' => $data['card'],
            'decks' => $decks
        ]);
    }

}

src/Controller/DeckCardsController.php
<?php

namespace App\Controller;

use App\Entity\Decks;
use App\Service\DeckService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class DeckCardsController extends AbstractController
{
    #[Route('decks/', name: 'decks')]
    public function getDecks(EntityManagerInterface $entityManager, DeckService $deckService)
    {

        $deckService = $entityManager->getRepository(Decks::class);
        $decks = $deckService->findAll();



        dd($decks);

        return 'TODO DECK LIST';
    }
}

src/Controller/DeckController.php
<?php

namespace App\Controller;

use App\Entity\DeckCards;
use App\Entity\Decks;
use App\Repository\DeckCardsRepository;
use App\Repository\DecksRepository;
use App\Service\DeckService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DeckController extends AbstractController
{

    #[Route('decks/', name: 'decks')]
    public function getDecks(EntityManagerInterface $entityManager)
    {

        $deckService = $entityManager->getRepository(Decks::class);
        $decks = $deckService->findAll();

        dd($decks);

        return 'TODO DECK LIST';
    }

    #[Route('decks/new')]
    public function newDeck()
    {
        return $this->render('deck/new.html.twig', [
            'title' => 'Your new MTG Deck',
        ]);
    }

    #[Route('decks/create', name: 'create_deck', methods: 'post')]
    public function createDeck(EntityManagerInterface $entityManager, Request $request): Response
    {
        $deck = new Decks();
        $deck->setName($request->request->get('name'));

        $entityManager->persist($deck);
        $entityManager->flush();

        return $this->redirectToRoute('add_cards', ['id' => $deck->getId()]);
    }

    #[Route('decks/{id}/cards', name: 'add_cards')]
    public function editDeckCards(int $id, DecksRepository $decksRepository, DeckCardsRepository $deckCardsRepository)
    {
        return $this->render('deck/add_cards.html.twig', [
            'title' => 'Your new MTG Deck',
            'deck' => $decksRepository->find($id)->getName(),
            'deckCards' => $deckCardsRepository->findBy(['deckId' => $id])
        ]);
    }

    #[Route('decks/add/card', name: 'add_to_deck', methods: ['post'])]
    public function addDeckCard(EntityManagerInterface $entityManager, Request $request)
    {
        $deckCard = new DeckCards();

        //dd($request);
        $deckCard->setCardId($request->request->get('card'));
        $deckCard->setDeckId($request->request->get('deck'));

        $entityManager->persist($deckCard);
        $entityManager->flush();

        return $this->redirectToRoute('cards');
    }

    #[Route('deck/{id}', name: 'deck', methods: ['get'])]
    public function deck(int $id, DeckCardsRepository $deckCardsRepository)
    {

        $deckCards = $deckCardsRepository->findBy(['deckId' => $id]);

        //TODO put every card id into an array. And pull all the information from API

        return $this->render('deck/view.html.twig', [
            'title' => 'Your Deck',
            'deckCards' => $deckCardsRepository->findBy(['deckId' => $id])
        ]);
    }
}

src/Controller/SetController.php
<?php

namespace App\Controller;

use App\Service\SetService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SetController extends AbstractController
{
    #[Route('sets/', name: 'sets')]
    public function getSets(Request $request, SetService $service): Response
    {
        $q = $request->query->get('q');
        $sets = $this->json($service->getAllSets($q)->toArray())->getContent();

        $data = json_decode($sets, true);

        return $this->render('set/list.html.twig', [
            'title' => 'MTG sets',
            'sets' => $data['sets'],
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}MTG Cards{% endblock %}</title>

    <link rel="apple-touch-icon" sizes="180x180" href="{{ asset('apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('favicon-16x16.png') }}">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('styles/app.css') }}">

    {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
    {% block stylesheets %}
        {{ encore_entry_link_tags('app') }}
    {% endblock %}

    {% block javascripts %}
        {{ encore_entry_script_tags('app') }}
    {% endblock %}
</head>
<body>

<!-- Main Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark  mb-5" style="background-color: #27333A;">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            MTG cards
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="#">Menu</a>
                </li>
                <!-- Not Authenticated -->
                <!-- <li class="nav-item"><button href="#" class="btn btn-primary btn-sm">Login</button></li> -->
                <!-- End Not Authenticated -->

                <!-- If Authenticated -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                       role="button" data-bs-toggle="dropdown" aria-expanded="false"> </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="#">My Decks</a></li>
                        <li><a class="dropdown-item" href="#">Signout</a></li>
                    </ul>
                </li>
                <!-- End If Authenticated -->
            </ul>
        </div>
    </div>
</nav>
<!-- End Main Navigation -->

{% block body %}{% endblock %}

<!-- Footer -->
<div class="container mt-5">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
            <span class="me-1" style="color: red;"><i class="fas fa-heart"></i></span>
        </div>

    </footer>
</div>
<!-- End Footer -->

</body>
</html>

templates/card/details.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="text-center">
            <h1>{{ card['name'] }} {% if card['manaCost'] is defined %} | {{ card['manaCost'] }} {% endif %}</h1>
            {% if card['imageUrl'] is defined %}
                <img class="card-list" src="{{ card['imageUrl'] }}">
            {% endif %}
            <br>
            <span>{{ card['type'] }} | {{ card['rarity'] }}<span><br>
            <span>{{ card['text'] }}

        </div>
    </div>
{% endblock %}

templates/card/homepage.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <h1>Card search</h1>

        <h2 class="mt-5 mb-4">Filter by Color</h2>
        <div class="row">
            <div class="col col-md-6">
                <ul class="genre-list ps-0 mt-2 mb-3">
                    <li class="d-inline">
                        <a class="btn btn-primary btn-sm" href="{{ path('app_homepage', {
                            color: 'W'
                        }) }}">White</a>
                    </li>
                    <li class="d-inline">
                        <a class="btn btn-primary btn-sm" href="{{ path('app_homepage', {
                            color: 'U'
                        }) }}">Blue</a>
                    </li>
                    <li class="d-inline">
                        <a class="btn btn-primary btn-sm" href="{{ path('app_homepage', {
                            color: 'B'
                        }) }}">Black</a>
                    </li>
                    <li class="d-inline">
                        <a class="btn btn-primary btn-sm" href="{{ path('app_homepage', {
                            color: 'R'
                        }) }}">Red</a>
                    </li>
                    <li class="d-inline">
                        <a class="btn btn-primary btn-sm" href="{{ path('app_homepage', {
                            color: 'G'
                        }) }}">Green</a>
                    </li>
                </ul>
            </div>
            <div class="col col-md-6">
                <div class="search">
                    <form action="{{ path('app_homepage') }}">
                        <input type="text" placeholder="Search..." id="query" name="q">
                        <button type="submit">Search</button>
                    </form>
                </div>
            </div>
        </div>

        <div>
            <h2 class="mt-5">Cards</h2>
            <div class="row">
                {% for card in cards %}
                    <div class="col col-md-4 text-center">
                        <a class="card-list" href="{{ path('app_card_details', {
                            id: card['id']
                        }) }}" class="mixed-vinyl-container p-3 text-center">
                            <h3>{{ card['name'] }}</h3>
                            {% if card['imageUrl'] is defined %}
                                <img class="card-list" src="{{ card['imageUrl'] }}">
                            {% endif %}
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/card/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <h1>Card search</h1>

        <h2 class="mt-5 mb-4">Filter by Color</h2>
        <div class="row">
            <div class="col col-md-6">
                <ul class="genre-list ps-0 mt-2 mb-3">
                    <li class="d-inline">
                        <a class="btn btn-primary btn-sm" href="{{ path('cards', {
                            color: 'W'
                        }) }}">White</a>
                    </li>
                    <li class="d-inline">
                        <a class="btn btn-primary btn-sm" href="{{ path('cards', {
                            color: 'U'
                        }) }}">Blue</a>
                    </li>
                    <li class="d-inline">
                        <a class="btn btn-primary btn-sm" href="{{ path('cards', {
                            color: 'B'
                        }) }}">Black</a>
                    </li>
                    <li class="d-inline">
                        <a class="btn btn-primary btn-sm" href="{{ path('cards', {
                            color: 'R'
                        }) }}">Red</a>
                    </li>
                    <li class="d-inline">
                        <a class="btn btn-primary btn-sm" href="{{ path('cards', {
                            color: 'G'
                        }) }}">Green</a>
                    </li>
                </ul>
            </div>
            <div class="col col-md-6">
                <div class="search">
                    <form action="{{ path('cards') }}">
                        <input type="text" placeholder="Search..." id="query" name="q">
                        <button type="submit">Search</button>
                    </form>
                </div>
            </div>
        </div>

        <div>
            <h2 class="mt-5">Cards</h2>
            <div class="row">
                {% for card in cards %}
                    <div class="col col-md-4 text-center">
                        <a class="card-list" href="{{ path('card_view', {
                            id: card['id']
                        }) }}" class="mixed-vinyl-container p-3 text-center">
                            <h3>{{ card['name'] }}</h3>
                            {% if card['imageUrl'] is defined %}
                                <img class="card-list" src="{{ card['imageUrl'] }}">
                            {% endif %}
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/card/view.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="text-center">
            <h1>{{ card['name'] }} {% if card['manaCost'] is defined %} | {{ card['manaCost'] }} {% endif %}</h1>
            {% if card['imageUrl'] is defined %}
                <img class="card-list" src="{{ card['imageUrl'] }}">
            {% endif %}
            <br>
            <span>{{ card['type'] }} | {{ card['rarity'] }}</span><br>
            <span>{{ card['text'] }}</span>

            <form action="{{ path('add_to_deck') }}" method="post">
                <label for="decks">Select deck:</label><br>
                <select name="deck" id="decks">

                    {% for deck in decks %}

                    <option value="{{ deck.id }}">{{ deck.name }}</option>
                    {% endfor %}
                </select>
                <input type="hidden" value="{{ card['id'] }}" name="card">
                <input type="submit" value="Submit">
            </form>
        </div>

    </div>
{% endblock %}

templates/deck/add_cards.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <h1>Deck: {{ deck }}</h1>




{#        <h2 class="mt-5 mb-4">Filter by Color</h2>#}
{#        <div class="row">#}
{#            <div class="col col-md-6">#}
{#                <ul class="genre-list ps-0 mt-2 mb-3">#}
{#                    <li class="d-inline">#}
{#                        <a class="btn btn-primary btn-sm" href="{{ path('cards', {#}
{#                            color: 'W'#}
{#                        }) }}">White</a>#}
{#                    </li>#}
{#                    <li class="d-inline">#}
{#                        <a class="btn btn-primary btn-sm" href="{{ path('cards', {#}
{#                            color: 'U'#}
{#                        }) }}">Blue</a>#}
{#                    </li>#}
{#                    <li class="d-inline">#}
{#                        <a class="btn btn-primary btn-sm" href="{{ path('cards', {#}
{#                            color: 'B'#}
{#                        }) }}">Black</a>#}
{#                    </li>#}
{#                    <li class="d-inline">#}
{#                        <a class="btn btn-primary btn-sm" href="{{ path('cards', {#}
{#                            color: 'R'#}
{#                        }) }}">Red</a>#}
{#                    </li>#}
{#                    <li class="d-inline">#}
{#                        <a class="btn btn-primary btn-sm" href="{{ path('cards', {#}
{#                            color: 'G'#}
{#                        }) }}">Green</a>#}
{#                    </li>#}
{#                </ul>#}
{#            </div>#}
{#            <div class="col col-md-6">#}
{#                <div class="search">#}
{#                    <form action="{{ path('cards') }}">#}
{#                        <input type="text" placeholder="Search..." id="query" name="q">#}
{#                        <button type="submit">Search</button>#}
{#                    </form>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}

{#        <div>#}
{#            <h2 class="mt-5">Cards</h2>#}
{#            <div class="row">#}
{#                {% for card in cards %}#}
{#                    <div class="col col-md-4 text-center">#}
{#                        <a class="card-list" href="{{ path('app_card_details', {#}
{#                            id: card['id']#}
{#                        }) }}" class="mixed-vinyl-container p-3 text-center">#}
{#                            <h3>{{ card['name'] }}</h3>#}
{#                            {% if card['imageUrl'] is defined %}#}
{#                                <img class="card-list" src="{{ card['imageUrl'] }}">#}
{#                            {% endif %}#}
{#                        </a>#}
{#                    </div>#}
{#                {% endfor %}#}
{#            </div>#}
{#        </div>#}
    </div>
{% endblock %}

templates/deck/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="text-center">
            <form action="{{ path('create_deck') }}" method="post">
                <label for="name">Deck title:</label><br>
                <input type="text" id="name" name="name" value="Mono aggro red"><br>
                <input type="submit" value="Submit">
            </form>
        </div>
    </div>
{% endblock %}

templates/deck/view.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <h1>Card search</h1>

        <h2 class="mt-5 mb-4">Filter by Color</h2>

        <div>
            <h2 class="mt-5">Cards</h2>
            <div class="row">
                {% for card in deckCards %}
                    <div class="col col-md-4 text-center">
                        {{ card.cardId }}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/set/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <h1>Set list</h1>

        <div class="col col-md-12">
            <div class="search">
                <form action="{{ path('sets') }}">
                    <input type="text" placeholder="Search..." id="query" name="q">
                    <button type="submit">Search</button>
                </form>
            </div>
        </div>

        <div>
            <h2 class="mt-5">Sets</h2>
            <table>
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Code</th>
                    <th>ReleaseDate</th>
                    <th>Expansion</th>
                </tr>
                </thead>
                <tbody>
                {% for set in sets %}
                    <tr>
                        <th>{{ set['name'] }}</th>
                        <th>{{ set['code'] }}</th>
                        <th>{{ set['releaseDate'] }}</th>
                        <th>{{ set['type'] }}</th>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}